# -*- coding: utf-8 -*-
"""abc.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PayXjyhzXagZvjgv-VJKPYnR7PabrQwv
"""

import math

radius = float(input("Enter the radius of the circle:"))
area = math.pi*radius**2

print(f"The area of the circle with radius{radius} is {area:2f}.")