# -*- coding: utf-8 -*-
"""Assignment 6 webscrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6P2oiPKurL-bxJNWoBu7kybMUj4rut1
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://en.wikipedia.org/wiki/2011_Indian_Premier_League"
response = requests.get(url)
html_content = response.content

soup = BeautifulSoup(html_content, 'html.parser')
table = soup.find('table', {'class':'wikitable sortable'})

df = pd.read_html(str(table))[0]

df.to_csv("ipl_2011_points_table.csv", index=False)