# -*- coding: utf-8 -*-
"""assignment 3 positive integer.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w6kFvVG3pob04s4rzuc90iLuOFbpQTay
"""

#define a function to filter positive numbers in a list 
def filter_positive_numbers(lst):
  #create an empty list to store positive numbers
  positive_lst=[]

  #iterate over the input list 
  for num in lst:
    #if the number is positive, add it to the positive list
    if num>0:
      positive_lst.append(num)

  #return the postive list
  return positive_lst

#prompt the user to enter a list of numbers
lst=input("Enter a list of numbers separated by commas:")

#convert the input string into a list of integers
lst=[int(num) for num in lst.split(',')]

#call the function and print the output
print(filter_positive_numbers(lst))