# -*- coding: utf-8 -*-
"""Assignment 2 fibonacci.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilnmmfJsB_-hHp6r9fdGTt6bxRcgzA8w
"""

#function to generate the Fibonacci sequenceup to n terms
def fibonacci (n):
  #initialize the first two terms of the sequence
  a, b = 0, 1

  #create an empty list to store the sequence
  fib_seq = []

  #generate the sequence upto n terms
  for i in range(n):
    #append the current term to the sequence
    fib_seq.append(a)

    #update the values of a and b for the next term
    a, b=b, a+b

  #return the generated sequence
  return fib_seq

#prompt the user to enter the number of terms they want in the sequence
n=int(input("Enter the number of terms you want in the Fibonacci sequence:"))

#example usage: print the first 10 terms of the sequence
print(fibonacci(n))